### ISSUE TITLE
Airlock Door mod doesn't work in Spaced Out. Period.

### ISSUE THREAD

**Issue by marsashworth** [peterhaneve/ONIMods#101] opened 2021-01-19 13:45 UTC
Airlock door mod is not working as intended in Oxygen Not Included Spaced Out

## Expected Behavior
The Spaced Out client should be able to use Airlock Doors as labelled on the Airlock Door mod page

## Current Behavior
![image](https://user-images.githubusercontent.com/37916331/105042295-f37dd080-5ac8-11eb-893b-cdf7bd8daa90.png)
<Also as indicated by many people on the steam mod page, the addon crashes the client if installed from the github>

## Mod Versions
Using the Github version, the client crashes anytime a duplicant tries to pass through a door
Using subscription installed version, the game doesn't recognize the mod as being compatible with Spaced Out and you can't click to enable it

Mod Updater doesn't work for Spaced Out

## Steps to Reproduce

1. Load the Spaced Out client in retail (not beta)
2. Wait for subscriptions to update. Click on the mods button and try to activate enable on Airlock Door.

**Comment by peterhaneve** [comment] 2021-01-20 01:41
Your mod list includes multiple mods (including Build Over Plants, Airlock Door, and Mod Updater) which have been updated to work for the DLC. If they all show as non-compatible, it is likely due to a wide-ranging Steam issue that Airlock Door cannot fix.

The entombment crash reported on Steam which occurs on GitHub versions is a bug in the base Spaced Out! DLC, and can be reproduced without any mods active. It was fixed by today's hotfix (https://forums.kleientertainment.com/game-updates/oni-so/448420-r1416/) but **only on the preview branch**.

**Closed by peterhaneve** 2021-01-20 01:41 UTC
