### ISSUE TITLE
Fast Track: Duplicant's skipping animations and teleporting after interacting

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#206] opened 2022-04-10 05:52 UTC
## Expected Behavior

The animation plays so duplicants aren't teleporting when climbing on ladder, dismounting from ladder to step through door, and step up a block animations.

## Current Behavior

I've noticed after updating to v0.2.12 duplicants are skipping the climbing on ladder, dismounting from ladder to step through door, and step up a block animations if they say hi or appreciate a friend just before doing so. The step up a block animation may also be skipping when delivering resources to blueprint's but I only just noticed that one as I was typing this up and am not as sure about it.

## Mod Versions

v0.2.12

## Steps to Reproduce

1. Watch for a duplicant to duplicant interaction around ladders/uneven surfaces
2. Notice duplicant teleport from ground up the ladder as they skip the animation after interacting with friends

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8458355/Player.log)

**Comment by peterhaneve** [comment] 2022-04-10 19:11
Due to the random nature of Duplicant interactions and the precise timing required, I have almost no hope of reliably reproducing the issue. As it appears to be only a visual glitch, is it something that is fixed by disabling "Animation Optimizations"?

**Comment by guildcrest** [comment] 2022-04-10 19:13
I'll check that if animation optimizations fix it but I can now reliably say that when supplying materials to blueprints next to uneven surfaces they teleport every time if they have to move up or down while supplying.

**Closed** 2022-04-11 18:49 UTC
Labels: bug
