### ISSUE TITLE
FastTrack latest version causes issues with hydra- unsure which option

### ISSUE THREAD

**Issue by Apprisco** [peterhaneve/ONIMods#330] opened 2023-03-24 10:52 UTC
## Expected Behavior
![image](https://user-images.githubusercontent.com/34324909/227501960-070d6227-0026-4a90-bb27-2a8742eb16f5.png)
Standard hydra, shouldn't have moving liquids or issues with electrolyzer flooding.
## Current Behavior
![image](https://user-images.githubusercontent.com/34324909/227502050-cdae80db-d5ef-4bf8-a472-253a192008b0.png)
However, getting around 70% electrolyzer uptime, and moving packets as seen above.
Disabling Fasttrack fixes the issue.

## Mod Versions
Latest version of fasttrack.

## Steps to Reproduce

1. Install FastTrack
2. Build Hydra
3. Observe.

**Comment by Apprisco** [comment] 2023-03-24 10:53
Update: FastTrack version 10.9.0, default options

**Comment by peterhaneve** [comment] 2023-03-25 05:15
Fast Track does not affect the Sim and thus cannot directly affect gas and liquid movement. What game speed multiplier is being used? Many systems in Oxygen Not Included have performance that depends on frame rate; if Fast Track affects the overall game frame rate, then some systems may work differently.

**Comment by Apprisco** [comment] 2023-03-25 06:06
I've already tested this at 1x up to 10x, there is a glitch somewhere. Without fasttrack even up to 10x it works perfectly,
With fasttrack, 1x to 10x all show the same issue.
I wish this wasn't an actual bug, I love the mod but had to disable it to get anywhere.

**Comment by peterhaneve** [comment] 2023-03-25 19:40
I cannot reproduce this issue in any form, at any game speed, with Fast Track either enabled or disabled. This is likely a race condition specific to your machine's CPU and memory layout.

My best guess is probably either trivial animation optimization (Faster Animations). You could also try Reduce Debris Checks.

**Comment by Apprisco** [comment] 2023-03-26 03:13
Interesting, i'll give it a go. My system is a 5950x running 4x16GBs of 3600 cl14 memory, though it probably isn't reproducible with different samples.

**Comment by Apprisco** [comment] 2023-03-26 03:22
Issue has been located. Reduce debris checks was the issue, not faster animations.
Could you try this again?

**Comment by Apprisco** [comment] 2023-03-26 03:27
UPDATE: finally found the whole issue.
I had the Efficient Supply mod installed, but the incompatible option unchecked in FastTrack.
Removing efficent supply completely, and reenabling the option has fixed the issue.
Seems like this is an issue with the two mods working together, interesting!

**Comment by peterhaneve** [comment] 2023-03-28 02:31
If this is just a compatibility issue I will close the issue for now, but the option will definitely be looked at. Thank you for the report!

**Closed by peterhaneve** 2023-03-28 02:31 UTC
Labels: enhancement
