### ISSUE TITLE
Deconstructing a Spacefarer Module with Fast Track crashes the game

### ISSUE THREAD

**Issue by von-skeltal** [peterhaneve/ONIMods#237] opened 2022-05-25 06:49 UTC
If the spacefarer module is the last module left on a rocket pad, Fast Track seems to crash the game when deconstructing it. 
## Expected Behavior
Normally there is a pretty big lag spike when deconstructing the module, but with Fast Track enabled it outright crashes.

I have Spaced Out enabled and am playing on the current live branch.

## Current Behavior
If there are other modules left, the spacefarer module deconstructs correctly, but if it's the last thing on the rocket pad, the game crashes to the error screen. The screen shows the following info: 
NullReferenceException: Object reference not set to an instance of an object

```
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.UpdateRoom (CavityInfo cavity) (at <f24b9af931d243e8acfe8fd803a68d06>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.RefreshRooms () (at <f24b9af931d243e8acfe8fd803a68d06>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber.Refresh () (at <f24b9af931d243e8acfe8fd803a68d06>:0)
PeterHan.FastTrack.GamePatches.BackgroundRoomProber+Refresh_Patch.Prefix () (at <f24b9af931d243e8acfe8fd803a68d06>:0)
(wrapper dynamic-method) RoomProber.RoomProber.Refresh_Patch1(RoomProber)
Grid.FreeGridSpace (Vector2I size, Vector2I offset) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ClusterManager.DeleteWorldObjects (WorldContainer world) (at <33cbadb4d53344698461e1b8bda03e57>:0)
ClusterManager+<>c__DisplayClass51_0.<DestoryRocketInteriorWorld>b__1 (System.Object obj) (at <33cbadb4d53344698461e1b8bda03e57>:0)
Scheduler.Update () (at <33cbadb4d53344698461e1b8bda03e57>:0)
GameScheduler.Update () (at <33cbadb4d53344698461e1b8bda03e57>:0)

```
Build: U41-498381-S

## Mod Versions
I'm using the latest public beta release of Fast Track, v0.3.9.0 , installed locally.

## Steps to Reproduce
1. Have a spacefarer module on a rocket pad with no other modules on that same pad; the interior of this module doesn't seem to matter with regards to this crash.
2. Deconstruct the module.

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/8768592/Player.log)

**Comment by peterhaneve** [comment] 2022-05-27 17:49
This issue is a duplicate of #234.

**Closed by peterhaneve** 2022-05-27 17:49 UTC
