### ISSUE TITLE
Stock Bug Fix: Aluminum disappears when sweeper tries to grab

### ISSUE THREAD

**Issue by zivvel** [peterhaneve/ONIMods#523] opened 2024-11-10 16:41 UTC
## Expected Behavior
Volcano erupts, releasing molten aluminum, sweeper (when allowed by automation) puts it in conveyor loader.

## Current Behavior
Volcano erupts, releasing molten aluminum, sweeper (when allowed by automation) tries to put it in conveyor loader. Debris is marked "In Use" but then disappears.

## Mod Versions
4.5.0.0 (via steam & Mod Updater)

## Steps to Reproduce
1. Enable only Stock Bug Fix mod
2. Load attached save 2024-11 Disco 132-Al [2024-11 Disco 132-Al.zip](https://github.com/user-attachments/files/17692236/2024-11.Disco.132-Al.zip)
3. Unpause; sweeper will load 10.8kg Al into loader (from previous eruption / fiddling with this)
4. Observe Al volcano eruption in about 13s
5. Sweeper will try to grab each newly-formed debris, but each will disappear and not get loaded
6. Can reconnect/disconnect automation on the sweeper to see that disappearance does not happen when sweeper is disabled

## Output Log
[Player.log](https://github.com/user-attachments/files/17692233/Player.log)

**Comment by peterhaneve** [comment] 2024-11-10 22:28
This is a side effect of the fix to https://forums.kleientertainment.com/klei-bug-tracker/oni/liquid-solidifying-into-existing-debris-gets-wrong-temperature-r24591 . Since Klei finally made the one line fix in the base game required to actually close this in the upcoming game update after nearly four years, it is not worth our time to try and debug this on the current version.

Please retest when this branch goes live and see if the issue still reproduces.

**Closed by peterhaneve** 2024-11-10 22:28 UTC
